version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2-console
    depends_on:
      - h2

  h2:
    image: oscarfonts/h2
    ports:
      - "1521:1521"
      - "81:81"
    volumes:
      - h2-data:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists

volumes:
  h2-data: