version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    environment:
      - JWT_SECRET_KEY=my-secret-key
      - JWT_ALGORITHM=HS256
    networks:
      - shop-network

  product-service:
    build: ./product-service
    ports:
      - "8001:8001"
    environment:
      - JWT_SECRET_KEY=my-secret-key
      - JWT_ALGORITHM=HS256
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge