version: '3.8'

services:
  user-service:
    build: user-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/shop_db
      - JWT_SECRET_KEY=my-secret-key
      - JWT_ALGORITHM=HS256
    depends_on:
      - database
    networks:
      - shop-network

  product-service:
    build: product-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/shop_db
      - JWT_SECRET_KEY=my-secret-key
      - JWT_ALGORITHM=HS256
    depends_on:
      - database
    networks:
      - shop-network

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

volumes:
  postgres_data: